language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: tL94dU0CH0zOMUjgYrBwehM6gbcziVq91YTr5xHd73PIuKWXysXpRQK0OkYKYtdJqKpnpVcBHTskb8/O2z42BANAxtqKXHWdBp/daLnMdNjhmfV3P626zQoYbwV4gcihpXUMrX8iRxvgEiC01KmW904tImEffS9CeUMovl9X5CPWC+9SjrgdJFeprn7tHGvLJhv0joEEvzhRF+Hz0dMy5gun2VORpBKC1pSXsJVrsQw61adtHiYDdE7CReVH8HHrDdvngYWZgGd5MNnOYrV1beD0tM7nLM73G5rQXRbenFOMs1MR7+ew0rx6GunIOMXl35qsU7h136HUTaLOITdx7fFYTlo0b9JgTIMTMuOVm8K9woIZJ4HmK/ZST8pfou87uqGe3kIbXdQxTz/REGhAIG1sLD7mZu77LeWpOuNEukK7bPS0RBQvQ+lat9uuI6NOb0DkwnUKZ21fuWUwh+R9OqGMYt/LG9eJtUnSeCC7Xmd/yk46FjLSPZJcMZPWiaiwRGWZX/kvBU0hCPe4yU1e3uh3lPIdGhetXGq5hTdNj8T2LbVix78vDlykh/t+gz4qZMmbkZey3SUuBWLe4ayCD+KtcByix707FvBKVDsnwVf8paHDrXkDhbvTifd42dOmO1D67yr7jQpw5UisxF7uHDmpEHsHk1ruXh3OBPkAe44=
